sessao_10/agenda/contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    
    # contact (CRUD)
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),

]

sessao_10/agenda/contact/views/contact_forms.py
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.utils import translation
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import login_required

from contact.forms import ContactForm
from contact.models import Contact


@login_required(login_url="contact:login")
def create(request):
    form_action = reverse("contact:create")
    if request.method == "POST":
        form = ContactForm(request.POST, request.FILES)
        context = {
            "form": form,
            "form_action": form_action,
            "title": _("Create Contact"),
            "html_language": translation.get_language(),
        }

        if form.is_valid():
            # form.save()
            # não salva no banco de dados, mas fica salvo na memória
            contact = form.save(commit=False)
            contact.owner = request.user
            # contact.show = False
            contact.save()
            return redirect("contact:update", contact_id=contact.pk)
        return render(
            request,
            "contact/create.html",
            context,
        )

    context = {
        "form": ContactForm(),
        "form_action": form_action,
        "title": _("Create Contact"),
        "html_language": translation.get_language(),
    }
    return render(
        request,
        "contact/create.html",
        context,
    )


@login_required(login_url="contact:login")
def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)
    form_action = reverse("contact:update", args=(contact_id,))
    if request.method == "POST":
        form = ContactForm(request.POST, request.FILES, instance=contact)
        context = {
            "form": form,
            "form_action": form_action,
            "title": _("Update Contact"),
            "html_language": translation.get_language(),
        }

        if form.is_valid():
            # form.save()
            # não salva no banco de dados, mas fica salvo na memória
            contact = form.save(commit=False)
            # contact.show = False
            contact.save()
            return redirect("contact:update", contact_id=contact.pk)
        return render(
            request,
            "contact/create.html",
            context,
        )

    context = {
        "form": ContactForm(instance=contact),
        "form_action": form_action,
        "title": _("Update Contact"),
        "html_language": translation.get_language(),
    }
    return render(
        request,
        "contact/create.html",
        context,
    )


@login_required(login_url="contact:login")
def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)
    confirmation = request.POST.get("confirmation", "no")
    context = {
        "contact": contact,
        "confirmation": confirmation,
        "title": _("Update Contact"),
        "html_language": translation.get_language(),
    }
    if confirmation == "yes":
        contact.delete()
        return redirect("contact:index")
    # contact.delete()
    # return redirect('contact:index')
    return render(request, "contact/contact.html", context)

sessao_10/agenda/contact/views/contact_views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import translation
from django.utils.translation import gettext as _
from django.db.models import Q
from django.core.paginator import Paginator

from contact.models import Contact


def index(request):
    contacts = Contact.objects.all().filter(show=True).order_by("-id")
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "title": _("Contacts"),
        "html_language": translation.get_language(),
        "page_obj": page_obj,
    }
    return render(
        request,
        "contact/index.html",
        context,
    )


def contact(request, contact_id):
    # consultando sem shortcuts
    # single_contact = Contact.objects.filter(pk=contact_id).first()
    # if single_contact is None:
    #     raise Http404

    # consultando com shortcuts
    # single_contact = get_object_or_404(Contact, pk=contact_id)
    single_contact = get_object_or_404(Contact.objects.filter(pk=contact_id, show=True))
    contact_name = f"{single_contact.first_name} {single_contact.last_name}"
    context = {
        "contact": single_contact,
        "title": f"{_('Contact')} {contact_name}",
        "html_language": translation.get_language(),
    }
    return render(
        request,
        "contact/contact.html",
        context,
    )


def search(request):
    search_term = request.GET.get("query", "").strip()
    if search_term == "":
        return redirect("contact:index")
    contacts = (
        Contact.objects.all()
        .filter(show=True)
        .filter(
            Q(first_name__icontains=search_term)
            | Q(last_name__icontains=search_term)
            | Q(phone__icontains=search_term)
            | Q(email__icontains=search_term)
        )
        .order_by("id")
    )
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        "title": _("Search"),
        "html_language": translation.get_language(),
        "search_term": search_term,
    }
    return render(
        request,
        "contact/index.html",
        context,
    )

sessao_10/agenda/contact/templates/contact/contact.html
{% extends "global/base.html" %}
{% load i18n %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ contact.first_name }} {{ contact.last_name }}
        </h1>

        <p><b>ID: </b> {{ contact.id }}</p>
        <p><b>{% translate "Phone" %}: </b> {{ contact.phone }}</p>
        <p><b>Email: </b> {{ contact.email }}</p>
        <p><b>{% translate "Created Date" %}: </b> {{ contact.created_date }}</p>
        <p><b>{% translate "Description" %}: </b> {{ contact.description }}</p>
        <p><b>{% translate "Category" %}: </b> {{ contact.category.name }}</p>

        {% if contact.picture %}
            <p>
                <img src="{{ contact.picture.url }}" alt="{{ contact.first_name }} {{ contact.last_name }}" srcset="">
            </p>
        {% endif %}
        {% if user == contact.owner %}
            <div class="contact-links">
                <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">{% translate "Update" %}</a>

                <form action="{% url 'contact:delete' contact.id %}" method="POST">
                    {% csrf_token %}
                    {% if confirmation == 'no' %}
                        <input type="hidden" name="confirmation" value="yes">
                        <button class="btn btn-link btn-delete" type="submit">{% translate "Confirm" %}?</button>
                    {% else %}
                        <button class="btn btn-link btn-delete" type="submit">{% translate "Delete" %}</button>
                    {% endif %}
                </form>
            </div>
        {% endif %}

    </div>
{% endblock content %}

sessao_10/agenda/contact/templates/contact/create.html
{% extends "global/base.html" %} 
{% load i18n %} 
{% block content %}
    <div class="form-wrapper">
        <h2>{% translate "Create Contact" %}</h2>
        <form action="{{ form_action}}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-content">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label}}">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}

                        {% if field.help_text %}
                            <p class="help-text">{{ field.help_text }}</p>
                        {% endif %}

                    </div>
                    {% if field.name == 'picture' and field.value.url %}
                        <div class="form-group">
                            <img src="{{ field.value.url}}" >
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            {% if form.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">
                            {{ form.non_field_errors }}
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">{% translate "Send" %}</button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

sessao_10/agenda/contact/templates/contact/index.html
{% extends "global/base.html" %} 
{% load i18n %}
{% block content %} 
{% if page_obj  %} 
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table caption">
                {% translate "Contacts" %}
            </caption>

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">{% translate "First Name" %}</th>
                    <th class="table-header">{% translate "Last Name" %}</th>
                    <th class="table-header">{% translate "Phone" %}</th>
                    <th class="table-header">E-mail</th>
                </tr>
            </thead>

            <tbody>
                {% for contact in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a href="{% url 'contact:contact' contact.id %}" class="table-link">{{ contact.id }}</a>
                        </td>
                        <td class="table-cel">
                            {{ contact.first_name }}
                        </td>
                        <td class="table-cel">
                            {{ contact.last_name }}
                        </td>
                        <td class="table-cel">
                            {{ contact.phone }}
                        </td>
                        <td class="table-cel">
                            {{ contact.email }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <div class="single-contact">
            <h1 class="single-contact-name">
                Nenhum contato encontrado
            </h1>

        </div>
    {% endif %}
{% endblock content %}

sessao_10/agenda/contact/templates/contact/login.html
{% extends 'global/base.html' %} 
{% block content %}
{% load i18n %} 
<div class="form-wrapper">
    <h2>Login</h2>

    {% if user.is_authenticated %}
    <p>
        {% translate "You are logged in as " %} {{ user.username }}.
        {% translate "Click" %} <a href="{% url "contact:logout" %}">{% translate "here" %}</a> {% translate "to logout" %}
    </p>
    {% else %}
        {% include "contact/partials/_user-form.html" %}
    {% endif %}
    </form>
</div>

{% endblock content %}

sessao_10/agenda/contact/templates/contact/register.html
{% extends 'global/base.html' %} 
{% load i18n %} 
{% block content %}

<div class="form-wrapper">
    <h2>{% translate "Register User" %}</h2>

    {% include "contact/partials/_user-form.html" %}
    </form>
</div>

{% endblock content %}

sessao_10/agenda/contact/templates/contact/user_update.html
{% extends 'global/base.html' %} 
{% load i18n %} 
{% block content %}

<div class="form-wrapper">
    <h2>{% translate "Update User" %}</h2>

    {% include "contact/partials/_user-form.html" %}
    </form>
</div>

{% endblock content %}